# Generated by Django 4.1.5 on 2023-02-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
