# Generated by Django 4.1.5 on 2023-02-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listings_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
