# Generated by Django 4.1.5 on 2023-02-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listings_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='image_url',
            new_name='image',
        ),
    ]
