# Generated by Django 4.1.5 on 2023-02-13 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_image_url_listings_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='image',
        ),
    ]
