# Generated by Django 4.1.5 on 2023-02-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_listings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
