# Generated by Django 4.1.5 on 2023-02-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_listings_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='listing',
            field=models.ManyToManyField(blank=True, related_name='listing', to='auctions.listings'),
        ),
    ]
