# Generated by Django 4.1.5 on 2023-02-16 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_bids_highest_bidder_listings_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='listings',
            name='item_comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_comments', to='auctions.comments'),
        ),
    ]
