# Generated by Django 4.1.5 on 2023-02-17 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_comments_commentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='listings',
            name='item_comments',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='comments',
            name='item_comments',
            field=models.ManyToManyField(blank=True, related_name='item_comments', to='auctions.listings'),
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auctions.categories'),
        ),
    ]
