# Generated by Django 4.1.5 on 2023-02-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_comments_commentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='item_comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='item_comments',
            field=models.ManyToManyField(blank=True, related_name='item_comments', to='auctions.listings'),
        ),
    ]
