# Generated by Django 4.1.5 on 2023-02-17 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_listings_item_comments_comments_item_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='watchlist',
        ),
    ]
