# Generated by Django 4.1.5 on 2023-02-17 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_categories_alter_listings_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
